### ISSUE TITLE
Not available any more?

### ISSUE THREAD

**Issue by cherimo** [NathanaelA/nativescript-zxing#28]
Hey Nathanael,

I get a 404 on the new home of zxing plugin when I try to add it in to my project, is it still available/maintained?

Greetz,

**Comment by NathanaelA** [comment]
The community version of Zxing is still available and has not changed.  You should be able to do a `npm i --save nativescript-zxing` and it will install.    I do not know the state of it, or if it even works with NS6.  The community has not sent any PR's for it since I think mid-2018.

I have put all my efforts into the open source sustainable [ProPlugins](https://npm.proplugins.org/-/web/detail/@proplugins/nativescript-zxing) version of Zxing which sees maintenance, and as such has had some additional fixes and changes and is guaranteed to work with NS6.
